project:
  type: website
  output-dir: docs # for GitHub pages
  render:
    - "*.qmd"

website:
  title: "CARDAT platform"
  navbar:
    # background: "#7c2a83"
    # foreground: "#FDECE2"
    left:
        - href: index.qmd
          text: "Home"
        
        - text: "About"
          menu:
            - href: placeholder.qmd
              text: "What we do"
            - href: about/infrastructure.qmd
              text: "Infrastructure"
            # - href: placeholder.qmd
            #   text: "Contributions to research"
        - text: "Using CARDAT"
          menu: 
            - href: user_guide/access.qmd
              text: "Accessing CARDAT resources"
            # - href: user_guide/overview.qmd
            #   text: "Overview"
            - href: user_guide/technical_guide.qmd
              text: "Technical Guide"
            - href: user_guide/data_access_request_form.qmd
              text: "Data Access Request Form"
            # - href: user_guide/data_science.qmd
            #   text: "Data Science Tips"  
          
        - text: "Data"
          menu:
            - href: placeholder.qmd
              text: "National Air Pollution Monitoring Database"
          
        - text: "Tools and workflows"
          menu:
            - href: placeholder.qmd
              text: "GitHub repository"
              
        - text: "Projects"
          menu:
            - href: projects/airhealth.qmd
              text: "AirHealth Data Bridges"
            
        - href: mailto:car.data@curtin.edu.au
          text: "Contact us"
          

format:
  html:
    theme:
      - cosmo
      - main.scss
    css: styles.css
    toc: true



